[build]
  base = "/" # Base is the root of the repository
  publish = "frontend/build" # The folder to deploy

  # NEW: Install dependencies from the frontend folder
  install = "cd frontend && npm install"

  # Changed: Build command also changes to the frontend folder
  command = "cd frontend && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200