[build]
  base = "frontend"  # Set the base to the frontend directory
  publish = "build"  # Publish the build folder from the base directory
  command = "npm run build"

# Add this section to install the plugin
[[plugins]]
  package = "netlify-plugin-node-modules"

[build.environment]
  NODE_VERSION = "18"  # Use a Node version compatible with your React app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200